In [1]:
import numpy as np
#creating the array using tuples
t=np.array((1,2,3))
print(t)
print("......")
t2=np.array([(1,2,3),(4,5,6)])
print(t2)

[1 2 3]
......
[[1 2 3]
 [4 5 6]]


In [2]:
l=np.array([1,2,3]) # row matrix using a list
print(l)
print('.......')
l2=np.array([[5,8,9],[1,3,7]])
l2

[1 2 3]
.......


array([[5, 8, 9],
       [1, 3, 7]])

In [15]:
# pre defined functions in arrays
print(type(l2)) # checking the type of variable l2
print(l2.dtype)
print(l2.shape)
print(l2.size)
print(l2.itemsize)
print(l2.ndim)
np.__version__ # checking the version of numpy

<class 'numpy.ndarray'>
int32
(2, 3)
6
4
2


'1.16.5'

In [46]:
#Creating the array using range()
r=np.array(range(9))
print(r)
r2=np.array(range(2,10))
print(r2)
r3=np.array(range(2,30,4))
r3

[0 1 2 3 4 5 6 7 8]
[2 3 4 5 6 7 8 9]


array([ 2,  6, 10, 14, 18, 22, 26])

### arange()
- arange()
- arange().reshape()

In [48]:
# Creating the array using arange() method
print(np.arange(5))
print(np.arange(5,20))
print(np.arange(5,30,3))
print(np.arange(20,4,-3))
print(np.arange(4,2,-0.5))

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  8 11 14 17 20 23 26 29]
[20 17 14 11  8  5]
[4.  3.5 3.  2.5]


In [61]:
ar=np.arange(25).reshape(5,5)
print(ar)
print('......')
ar2=np.arange(10,40).reshape(6,-1)
print(ar2)
print('........')
ar3=np.arange(24).reshape(-1,6)
print(ar3)
ar4=np.arange(10,40).reshape(5,6)
print(ar4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
......
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
........
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]


In [6]:
# using linspace
print(np.linspace(10,20,5)) # partitioning the range with 3rd argument
print(np.linspace(3,9,4)) # both limits are inclusive

[10.  12.5 15.  17.5 20. ]
[3. 5. 7. 9.]


In [18]:
# Creating the array with 0s,1s and full
o=np.ones((2,3))
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
f=np.full((3,2),5)
print(f)
print('....')
z.fill(9) # it will accept only floating values
z

[[5 5]
 [5 5]
 [5 5]]
....


array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [24]:
st=np.array([['hi','hello','hey'],[12,34,67],[9.3,8.5,5]])
print(st)
type(st) # 00 11 22 33
st.dtype # numpy attribute

[['hi' 'hello' 'hey']
 ['12' '34' '67']
 ['9.3' '8.5' '5']]


dtype('<U5')

In [25]:
np.diag(st) # giving the diagonal elements of st

array(['hi', '34', '5'], dtype='<U5')

In [12]:
np.eye(4) # creating identity matrix 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
print(np.diag([1,2,3,4])) # creating the diagonal matrix

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### Random
- generates random values in a range
    - random.randint() generates a random value# 
        - random.randint(,)
        - random.randint(,,)
        - random.randint(,()) # matrix
    - random.random(())
    - random.rand(,)
    - random.randn(,)

In [8]:
import numpy as np
r=np.random.randint(10) # from 0 to 10
print(r)
r2=np.random.randint(10,40)
print(r2) # 10 and 40
r3=np.random.randint(10,50,6) # generates 6 values in this range
print(r3) # row matrix
r4=np.random.randint(10,100,(2,4)) # generate random array of size (2,4)
print(r4)
arn=np.random.randint(10,50,12).reshape(4,3) # reshaping the random matrix also
print(arn)

7
32
[17 11 39 17 18 41]
[[52 44 60 90]
 [16 92 78 86]]
[[44 11 48]
 [13 17 10]
 [47 11 29]
 [36 32 39]]


In [16]:
rn=np.random.random((2,4)) # 0 to 1
rn # standard deviation values randomly between 0 and 1 of size 2x4

array([[0.6571003 , 0.10410643, 0.39570021, 0.94922555],
       [0.3797253 , 0.20022839, 0.87097018, 0.15850619]])

In [15]:
rd=np.random.rand(3,2) # generates standard deviation values randomly 
rd # between 0 and

array([[0.83617219, 0.09582083],
       [0.01622443, 0.98133694],
       [0.34013625, 0.25236303]])

In [17]:
rdn=np.random.randn(3,2) # from -1 to 1
rdn

array([[-0.62492902,  1.41951058],
       [-0.40439341, -0.77198134],
       [ 1.07828599,  0.12201204]])

In [33]:
rnm=np.random.normal(2,1)
rnm # normalized values

3.6326458101282166

In [35]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

### Slicing
- Index based slicing
- Fancy indexing

In [26]:
r5=np.random.randint(10,100,(4,4))
r5

array([[71, 90, 61, 76],
       [73, 58, 56, 71],
       [29, 63, 54, 42],
       [34, 85, 84, 37]])

In [28]:
r5[:]

array([[71, 90, 61, 76],
       [73, 58, 56, 71],
       [29, 63, 54, 42],
       [34, 85, 84, 37]])

In [29]:
r5[:3]

array([[71, 90, 61, 76],
       [73, 58, 56, 71],
       [29, 63, 54, 42]])

In [30]:
r5[2:]

array([[29, 63, 54, 42],
       [34, 85, 84, 37]])

In [31]:
# restriction on both rows and columns
r5[2:,:3]

array([[29, 63, 54],
       [34, 85, 84]])

In [32]:
r5>40 # fancy indexing results in boolean matrix

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [False,  True,  True, False]])

In [65]:
r5

array([[66, 88, 83, 26],
       [62, 45, 36, 38],
       [53, 16, 10, 91],
       [49, 72, 13, 85]])

In [33]:
r5[r5>50]

array([71, 90, 61, 76, 73, 58, 56, 71, 63, 54, 85, 84])

In [67]:
r5[r5>50]

array([66, 88, 83, 62, 53, 91, 72, 85])

In [69]:
r5[r5>50].sum()

600

In [78]:
r5

array([[66, 88, 83, 26],
       [62, 45, 36, 38],
       [53, 16, 10, 91],
       [49, 72, 13, 85]])

In [80]:
ar2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [82]:
np.expand_dims(ar2,axis=3)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24]],

       [[25],
        [26],
        [27],
        [28],
        [29]],

       [[30],
        [31],
        [32],
        [33],
        [34]],

       [[35],
        [36],
        [37],
        [38],
        [39]]])

### Mathematical Operations

In [3]:
import numpy as np
ar=np.arange(25).reshape(5,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
m=np.random.randint(30,60,(5,5))
m

array([[39, 50, 40, 41, 46],
       [58, 49, 40, 42, 44],
       [55, 42, 50, 34, 35],
       [36, 32, 36, 56, 58],
       [41, 47, 38, 42, 36]])

In [5]:
print(ar+m)
print('.......')
print(m-ar)
print('......')
print(ar*m)
print('......')
print(m/ar)
print('........')
print(np.min(m))
print('........')
print(np.max(ar))

[[39 51 42 44 50]
 [63 55 47 50 53]
 [65 53 62 47 49]
 [51 48 53 74 77]
 [61 68 60 65 60]]
.......
[[39 49 38 38 42]
 [53 43 33 34 35]
 [45 31 38 21 21]
 [21 16 19 38 39]
 [21 26 16 19 12]]
......
[[   0   50   80  123  184]
 [ 290  294  280  336  396]
 [ 550  462  600  442  490]
 [ 540  512  612 1008 1102]
 [ 820  987  836  966  864]]
......
[[        inf 50.         20.         13.66666667 11.5       ]
 [11.6         8.16666667  5.71428571  5.25        4.88888889]
 [ 5.5         3.81818182  4.16666667  2.61538462  2.5       ]
 [ 2.4         2.          2.11764706  3.11111111  3.05263158]
 [ 2.05        2.23809524  1.72727273  1.82608696  1.5       ]]
........
32
........
24


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys


### Scientific Computation

In [6]:
print(np.mean(m)) # no.of elements/sum
print(np.std(m))
print(np.median(ar)) # middle element x+y/2
print(ar.dot(m)) # multiplies both matrices 

43.48
7.483956173041101
12.0
[[ 440  417  400  446  432]
 [1585 1517 1420 1521 1527]
 [2730 2617 2440 2596 2622]
 [3875 3717 3460 3671 3717]
 [5020 4817 4480 4746 4812]]


### Broadcasting
- huge conversion
- applying a single vector/value on iterable 

In [8]:
print(ar+5) # applying a single value on iterable
print(ar*4) # entire variable by applying a single value
print(ar/3)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 0  4  8 12 16]
 [20 24 28 32 36]
 [40 44 48 52 56]
 [60 64 68 72 76]
 [80 84 88 92 96]]
[[0.         0.33333333 0.66666667 1.         1.33333333]
 [1.66666667 2.         2.33333333 2.66666667 3.        ]
 [3.33333333 3.66666667 4.         4.33333333 4.66666667]
 [5.         5.33333333 5.66666667 6.         6.33333333]
 [6.66666667 7.         7.33333333 7.66666667 8.        ]]


### Logarithms and Exponentials
- np.log(ele)
- np.exp(ele)

In [9]:
np.log(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [10]:
np.log(1)

0.0

In [11]:
np.log(10)

2.302585092994046

In [12]:
np.log(2)

0.6931471805599453

In [13]:
np.log2(2)

1.0

In [14]:
np.log2(10)

3.321928094887362

In [15]:
np.log([2,3,4])

array([0.69314718, 1.09861229, 1.38629436])

In [16]:
np.exp(1)

2.718281828459045

In [112]:
np.exp(2)

7.38905609893065

In [113]:
np.exp(2)-1

6.38905609893065

In [116]:
np.exp([2,3])

array([ 7.3890561 , 20.08553692])

### Vectorize functions
- The fuunctions of Numpy which can be applied on any variable

In [46]:
def greater(a,b):
    if a>b:
        return a
    else: return b
    
greater(4,10)

10

In [120]:
greater(10,21)

21

In [121]:
greater([23,4,19],[9,45,3]) # [23,45,19]

[23, 4, 19]

In [122]:
greater([67,23,45],[90,56,2])

[90, 56, 2]

In [54]:
v=np.vectorize(greater)
print(v) # when you call empty class

In [43]:
dir(np.log)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

In [55]:
help(np.vectorize)

Help on class vectorize in module numpy:

class vectorize(builtins.object)
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False, signature=None)
 |  
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,
 |            signature=None)
 |  
 |  Generalized function class.
 |  
 |  Define a vectorized function which takes a nested sequence of objects or
 |  numpy arrays as inputs and returns a single numpy array or a tuple of numpy
 |  arrays. The vectorized function evaluates `pyfunc` over successive tuples
 |  of the input arrays like the python map function, except it uses the
 |  broadcasting rules of numpy.
 |  
 |  The data type of the output of `vectorized` is determined by calling
 |  the function with the first element of the input.  This can be avoided
 |  by specifying the `otypes` argument.
 |  
 |  Parameters
 |  ----------
 |  pyfunc : callable
 |      A python function or method.
 |  otypes : str or list of dtypes, optional
 |      The 

In [56]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a>b:return a-b
    else:return a+b
    
myfunc(5,6)

11

In [61]:
vp=np.vectorize(myfunc)
myfunc([8,2,10,5],4)

TypeError: '>' not supported between instances of 'list' and 'int'