### Today Topics
- Numpy 
- Git&Github

### Numpy
- Numerical Python
- array type of data
- homogenous data
- creating the arrays
- scientific computation
- mean,standard deviation,co varience,logarithms,exponentials
- **Numpy Installation**
    - pip install numpy
    - import numpy 
- numpy.array() # list,tuple etc.

In [5]:
import numpy as n # numpy everytime , n
dir(n)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [4]:
n.version

<module 'numpy.version' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [7]:
# creating arrays with tuple
t=n.array((1,2,3)) # row matrix
print(t)# tuples

[1 2 3]


In [8]:
# list of values are separated by ,
li=[1,2,3,4]
li

[1, 2, 3, 4]

In [19]:
# column matrix using tuple
t2=n.array([(1),(2),(3),(4)]) # single tuple
t2

array([1, 2, 3, 4])

In [17]:
l=n.array([[1],[2],[3]]) # list of lists
l # column matrix

array([[1],
       [2],
       [3]])

In [20]:
# 2x3 array creating using tuple and list
lt=n.array([(1,2,5),(3,4,6)])
print(lt)

[[1 2 5]
 [3 4 6]]


In [22]:
tl=n.array((['hi',1],[4,5])) # 3 int and 1 str
print(tl)

[['hi' '1']
 ['4' '5']]


In [25]:
print(type(tl)) # checking the type of variable tl
print(tl.dtype) # data types in tl variable
print(tl.shape) # rowxcolm
print(tl.size) # no.of items in array
print(tl.itemsize) # size of each item in array
print(tl.ndim) # dimenstions of array
n.__version__ # -- represents what constructor of the class

<class 'numpy.ndarray'>
<U2
(2, 2)
4
8
2


'1.16.5'

In [26]:
dir(n)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [27]:
help(n.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [30]:
# creating arrays using range() 
print(n.array(range(10)))
print(n.array(range(10,45)))
print(n.array(range(1,50,5)))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44]
[ 1  6 11 16 21 26 31 36 41 46]


In [67]:
# creating the arrays using arange() # sub module in numpy
ar=n.arange(1,31)
print(ar)
print(n.arange(10,50))
print(n.arange(10,60,3))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58]


In [36]:
# we can reshape our array
# by using reshape() sub module in array
re=n.arange(10,50).reshape(5,8) # 40 ele
re

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49]])

In [40]:
r2=n.arange(10,40).reshape(3,-1) # both row & colm
r2

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [44]:
# no.of columns
c=n.arange(10,40,2).reshape(-5,5) # unknown value is represented with -ve value
c

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [47]:
count=0
for num in range(10,20,2):
    print(num,end=" ")
    count+=1
count

10 12 14 16 18 

5

In [50]:
# using linspace
print(n.linspace(10,20,5)) # range(st,stp,step)
print(n.linspace(3,9,4)) 

[10.  12.5 15.  17.5 20. ]
[3. 5. 7. 9.]


In [53]:
# creating ones matrix
o=n.ones((4,3)) # creaing 4x3 array 
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [54]:
o2=n.ones(3) # row matrix
o2

array([1., 1., 1.])

In [55]:
z=n.zeros((2,3)) # creating zero matrix
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
# identity matrix
e=n.eye(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
f=n.full((3,3),5) # size,ele
f

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [63]:
z.fill(9) # zero matrix

In [64]:
z # with 9

array([[9., 9., 9.],
       [9., 9., 9.]])

### Array Slicing
- slicing by using default/formal index
- using fancy index

In [68]:
ar.size

30

In [69]:
r=ar.reshape(3,10)
print(r)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [70]:
r[2] # 3rd row in matrix

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [71]:
r[-1] # last row

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [72]:
# 2d in6dexing
r[2][5] # value at 6th in 3rd row

26

In [74]:
# rows and cols
#array[row,col] # dividing the iterable using some perticular range
r[:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [75]:
r[::]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [77]:
r[:2] # 0 to 1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [78]:
r[1:2]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [79]:
r[1:1] # null matrix

array([], shape=(0, 10), dtype=int32)

In [82]:
r[:2,3:6] # all rows,4 to 7

array([[ 4,  5,  6],
       [14, 15, 16]])

In [83]:
n.diag(r) # 3x10 

array([ 1, 12, 23])

In [84]:
r

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [85]:
print(n.diag([1,2,3,4,5])) # diagonal matrix

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Random matrix
- array with random values
- np.random()

In [100]:
import numpy as np
r=np.random.randint(10) # from 0 to 10
print(r)
r2=np.random.randint(10,40)
print(r2)
r3=np.random.randint(10,50,6) # 6 random values
print(r3)
r4=np.random.randint(10,100,(2,4)) #2x4
print(r4)
r5=np.random.randint(50,100,10).reshape(2,5)
print(r5)

6
25
[32 35 33 40 14 34]
[[57 72 99 81]
 [96 73 20 39]]
[[76 92 79 59 83]
 [77 80 62 51 96]]
